### ISSUE TITLE
Hard crash on "import into current loadout" since 10.0.7

### ISSUE THREAD

**Issue by Mazwak** [Numynum/TalentTreeTweaks#22] opened 2023-03-27 16:52 UTC
Hello

Since last patch (10.0.7), I experience a hard crash when I try to import into current loadout.

I think there is a bug in WoW, but you might find a workaround.

![image](https://user-images.githubusercontent.com/120138/228011107-9af01e22-1093-48df-8b4f-b430ce9771a7.png)

**Comment by Mazwak** [comment] 2023-04-10 09:36
After a few tests, not all make it crash.

OK

- Hunter marksmanship wowhead m+
- Hunter beast master icy-veins m+
- Shaman elemental wowhead m+ wildfire
- Shaman enhance wowhead aoe elem
- DH havoc wowhead glaive tempest

Crash:

- Monk Windwalker wowhead cleave (tried thrice)

I deleted all loadouts from wy windwalker, and tried again. Still crash.

If I find other specs with the problem, I will report.

**Comment by Numynum** [comment] 2023-04-10 11:33
I see, the windwalker build from wowhead has an error
the string they give you is `B0QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQSkkEtISEAAAAIRSSIBIJJCJlkERCJkkkk0SAAAA`
but the correct export is `B0QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQSkkEtISEAAAAIRSShEgkkIkUSSEJkQSSSSLBAAAA`

I'll see what I can do about it, to prevent a crash

**Comment by Numynum** [comment] 2023-04-10 12:26
caused by https://github.com/Stanzilla/WoWUIBugs/issues/419, fixed in next update

**Closed** 2023-04-10 12:26 UTC

**Comment by Mazwak** [comment] 2023-04-10 13:24
Thanks for the quick fix
